package database

var quantResearchMigrationStatements = []string{
	`CREATE TABLE IF NOT EXISTS quant_events (
		id char(64) PRIMARY KEY,
		event_type varchar(48) NOT NULL,
		target_scope varchar(24) NOT NULL,
		current_version integer NOT NULL DEFAULT 1,
		first_known_at timestamptz NOT NULL,
		first_ingested_at timestamptz NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		updated_at timestamptz NOT NULL DEFAULT now()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_events_type_scope ON quant_events (event_type, target_scope)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_events_first_known_at ON quant_events (first_known_at DESC)`,
	`CREATE TABLE IF NOT EXISTS quant_event_versions (
		id bigserial PRIMARY KEY,
		event_id char(64) NOT NULL REFERENCES quant_events(id) ON DELETE CASCADE,
		version integer NOT NULL,
		content_hash char(64) NOT NULL,
		status varchar(20) NOT NULL,
		title text NOT NULL,
		summary text,
		impact varchar(16),
		strength varchar(16),
		horizon varchar(24),
		expected_at timestamptz,
		announced_at timestamptz,
		effective_at timestamptz,
		expires_at timestamptz,
		known_at timestamptz NOT NULL,
		ingested_at timestamptz NOT NULL,
		known_at_basis varchar(32) NOT NULL,
		source_tier varchar(16) NOT NULL,
		source_name varchar(120),
		source_url text,
		source_published_at timestamptz,
		source_confidence varchar(16),
		raw_payload jsonb NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (event_id, version)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_event_versions_as_of ON quant_event_versions (event_id, known_at DESC, version DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_event_versions_status ON quant_event_versions (status, known_at DESC)`,
	`CREATE TABLE IF NOT EXISTS quant_event_assets (
		id bigserial PRIMARY KEY,
		event_id char(64) NOT NULL REFERENCES quant_events(id) ON DELETE CASCADE,
		asset_type varchar(24) NOT NULL,
		asset_code varchar(32) NOT NULL,
		mapping_basis varchar(64),
		weight_hint numeric(10,4),
		created_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (event_id, asset_type, asset_code)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_event_assets_lookup ON quant_event_assets (asset_type, asset_code)`,
	`CREATE TABLE IF NOT EXISTS quant_instruments (
		symbol varchar(32) PRIMARY KEY,
		name varchar(120) NOT NULL,
		exchange varchar(16) NOT NULL,
		asset_class varchar(24) NOT NULL,
		universe_group varchar(32),
		tracking_index varchar(32),
		listed_at date,
		delisted_at date,
		source varchar(32) NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		updated_at timestamptz NOT NULL DEFAULT now()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_instruments_group ON quant_instruments (asset_class, universe_group)`,
	`CREATE TABLE IF NOT EXISTS quant_universe_members (
		id bigserial PRIMARY KEY,
		universe_version varchar(32) NOT NULL,
		symbol varchar(32) NOT NULL REFERENCES quant_instruments(symbol),
		bucket varchar(32) NOT NULL,
		included_at timestamptz NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (universe_version, symbol)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_universe_members_version ON quant_universe_members (universe_version, bucket)`,
	`CREATE TABLE IF NOT EXISTS quant_market_bars (
		id bigserial PRIMARY KEY,
		symbol varchar(32) NOT NULL REFERENCES quant_instruments(symbol),
		date date NOT NULL,
		open numeric(18,6) NOT NULL,
		high numeric(18,6) NOT NULL,
		low numeric(18,6) NOT NULL,
		close numeric(18,6) NOT NULL,
		adjusted_close numeric(18,6) NOT NULL,
		volume numeric(24,4) NOT NULL,
		amount numeric(24,4) NOT NULL,
		adjust_factor numeric(20,10) NOT NULL DEFAULT 1,
		suspended boolean NOT NULL DEFAULT false,
		source varchar(32) NOT NULL,
		ingested_at timestamptz NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		updated_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (symbol, date)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_market_bars_date ON quant_market_bars (date DESC, symbol)`,
	`CREATE TABLE IF NOT EXISTS quant_corporate_actions (
		id bigserial PRIMARY KEY,
		symbol varchar(32) NOT NULL REFERENCES quant_instruments(symbol),
		action_date date NOT NULL,
		action_type varchar(24) NOT NULL,
		cash_amount numeric(18,6),
		split_factor numeric(20,10),
		source varchar(32) NOT NULL,
		known_at timestamptz NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (symbol, action_date, action_type)
	)`,
	`CREATE TABLE IF NOT EXISTS quant_trading_calendar (
		id bigserial PRIMARY KEY,
		market varchar(16) NOT NULL,
		date date NOT NULL,
		is_open boolean NOT NULL,
		reason varchar(80),
		source varchar(32) NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		updated_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (market, date)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_trading_calendar_open ON quant_trading_calendar (market, is_open, date)`,
	`CREATE TABLE IF NOT EXISTS quant_signal_history (
		id bigserial PRIMARY KEY,
		fund_id varchar(10) NOT NULL,
		analysis_version varchar(32) NOT NULL,
		signal_date date NOT NULL,
		mode varchar(32) NOT NULL,
		decision_at timestamptz NOT NULL,
		data_cutoff_at timestamptz NOT NULL,
		total_score numeric(8,4) NOT NULL,
		shadow_event_score numeric(8,4),
		input_json jsonb NOT NULL,
		output_json jsonb NOT NULL,
		event_ids jsonb NOT NULL,
		created_at timestamptz NOT NULL DEFAULT now(),
		UNIQUE (fund_id, analysis_version, signal_date, mode)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_signal_history_decision ON quant_signal_history (decision_at DESC, fund_id)`,
	`CREATE TABLE IF NOT EXISTS quant_backtest_jobs (
		id char(32) PRIMARY KEY,
		idempotency_key char(64) NOT NULL UNIQUE,
		status varchar(20) NOT NULL,
		strategy varchar(48) NOT NULL,
		universe_version varchar(32) NOT NULL,
		signal_mode varchar(32) NOT NULL,
		engine varchar(24) NOT NULL,
		engine_version varchar(80),
		parameters_json jsonb NOT NULL,
		metrics_json jsonb,
		equity_json jsonb,
		trades_json jsonb,
		benchmarks_json jsonb,
		log_summary text,
		error_message text,
		attempt_count integer NOT NULL DEFAULT 0,
		created_at timestamptz NOT NULL DEFAULT now(),
		started_at timestamptz,
		completed_at timestamptz,
		updated_at timestamptz NOT NULL DEFAULT now()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_quant_backtest_jobs_status ON quant_backtest_jobs (status, created_at)`,
}
